export const hardestVocabularyWords = [
    { word: "Aberration", meaning: "A departure from what is normal or expected" },
    { word: "Acrimony", meaning: "Bitterness or ill feeling" },
    { word: "Ambivalence", meaning: "Mixed feelings or contradictory ideas about something" },
    { word: "Anachronism", meaning: "Something belonging to a different time period" },
    { word: "Antithesis", meaning: "A direct opposite" },
    { word: "Apocryphal", meaning: "Of doubtful authenticity" },
    { word: "Assiduous", meaning: "Showing great care and perseverance" },
    { word: "Beguile", meaning: "To charm or enchant, often in a deceptive way" },
    { word: "Belligerent", meaning: "Hostile and aggressive" },
    { word: "Capricious", meaning: "Given to sudden changes in mood or behavior" },
    { word: "Cacophony", meaning: "A harsh, discordant mixture of sounds" },
    { word: "Circumlocution", meaning: "The use of many words to say something simple" },
    { word: "Circumspect", meaning: "Wary and unwilling to take risks" },
    { word: "Clandestine", meaning: "Kept secret or done secretly" },
    { word: "Cogent", meaning: "Clear, logical, and convincing" },
    { word: "Conflagration", meaning: "A large and destructive fire" },
    { word: "Conundrum", meaning: "A confusing and difficult problem" },
    { word: "Cryptic", meaning: "Having a meaning that is mysterious or obscure" },
    { word: "Debacle", meaning: "A sudden and complete failure" },
    { word: "Deference", meaning: "Respectful submission or yielding to others" },
    { word: "Deluge", meaning: "A severe flood or overwhelming rush" },
    { word: "Diatribe", meaning: "A forceful and bitter verbal attack" },
    { word: "Dichotomy", meaning: "A division into two contrasting things" },
    { word: "Disparage", meaning: "To belittle or undervalue" },
    { word: "Eclectic", meaning: "Deriving ideas from a diverse range of sources" },
    { word: "Ebullient", meaning: "Overflowing with enthusiasm or excitement" },
    { word: "Efficacious", meaning: "Effective; producing the desired outcome" },
    { word: "Ephemeral", meaning: "Lasting for a very short time" },
    { word: "Epitome", meaning: "A perfect example of something" },
    { word: "Esoteric", meaning: "Intended for a small, specialized audience" },
    { word: "Euphemism", meaning: "A mild expression substituted for a harsh one" },
    { word: "Exacerbate", meaning: "To make a bad situation worse" },
    { word: "Exorbitant", meaning: "Unreasonably high" },
    { word: "Facetious", meaning: "Treating serious issues with inappropriate humor" },
    { word: "Fastidious", meaning: "Very attentive to detail" },
    { word: "Furtive", meaning: "Secretive and avoiding notice" },
    { word: "Garner", meaning: "To gather or collect" },
    { word: "Garrulous", meaning: "Excessively talkative" },
    { word: "Grandiloquent", meaning: "Pompous or extravagant in language" },
    { word: "Hapless", meaning: "Unfortunate or unlucky" },
    { word: "Harangue", meaning: "A lengthy and aggressive speech" },
    { word: "Iconoclast", meaning: "Someone who challenges traditional beliefs" },
    { word: "Idiosyncratic", meaning: "Peculiar or individual" },
    { word: "Immutable", meaning: "Unchanging over time" },
    { word: "Imperious", meaning: "Arrogant and domineering" },
    { word: "Impetuous", meaning: "Acting quickly without thought" },
    { word: "Inchoate", meaning: "Not fully developed or organized" },
    { word: "Indolent", meaning: "Wanting to avoid activity; lazy" },
    { word: "Ineffable", meaning: "Too great to be expressed in words" },
    { word: "Inimical", meaning: "Harmful or hostile" },
    { word: "Insidious", meaning: "Proceeding subtly but with harmful effects" },
    { word: "Intransigent", meaning: "Unwilling to change views" },
    { word: "Inveterate", meaning: "Having a long-standing habit" },
    { word: "Juxtaposition", meaning: "Placing things side by side for comparison" },
    { word: "Languid", meaning: "Lacking energy or vitality" },
    { word: "Lugubrious", meaning: "Looking or sounding sad" },
    { word: "Magnanimous", meaning: "Generous and forgiving" },
    { word: "Malevolent", meaning: "Having or showing a wish to harm others" },
    { word: "Malfeasance", meaning: "Wrongdoing, especially by a public official" },
    { word: "Mellifluous", meaning: "Sweet-sounding or pleasing to the ear" },
    { word: "Mercurial", meaning: "Subject to sudden mood changes" },
    { word: "Mitigate", meaning: "To make less severe" },
    { word: "Misanthrope", meaning: "A person who dislikes others" },
    { word: "Myopic", meaning: "Lacking foresight or imagination" },
    { word: "Nascent", meaning: "Just coming into existence" },
    { word: "Nebulous", meaning: "Unclear or vague" },
    { word: "Obfuscate", meaning: "To make something unclear or difficult to understand" },
    { word: "Obsequious", meaning: "Excessively obedient or servile" },
    { word: "Ostensible", meaning: "Appearing to be true but not necessarily so" },
    { word: "Parsimony", meaning: "Extreme unwillingness to spend money" },
    { word: "Perfunctory", meaning: "Done without care or interest" },
    { word: "Propensity", meaning: "A natural tendency to behave a certain way" },
    { word: "Quixotic", meaning: "Unrealistically idealistic" },
    { word: "Recalcitrant", meaning: "Resisting authority or control" },
    { word: "Recondite", meaning: "Not easily understood; obscure" },
    { word: "Sagacious", meaning: "Wise or showing good judgment" },
    { word: "Sycophant", meaning: "A person who flatters for personal gain" },
    { word: "Taciturn", meaning: "Reserved or saying little" },
    { word: "Temerity", meaning: "Excessive boldness or confidence" },
    { word: "Tenuous", meaning: "Weak or insubstantial" },
    { word: "Ubiquitous", meaning: "Present everywhere" },
    { word: "Vacillate", meaning: "To waver between different opinions" },
    { word: "Vehement", meaning: "Showing strong and intense emotion" },
    { word: "Venerate", meaning: "To regard with great respect" },
    { word: "Voracious", meaning: "Wanting or devouring great quantities of food or knowledge" },
    { word: "Zealot", meaning: "A fanatically devoted person" }
  ];
  

  export const advancedVocabularyWords = [
    { word: "Adept", meaning: "Highly skilled or proficient" },
    { word: "Ambiguous", meaning: "Having more than one possible meaning" },
    { word: "Ample", meaning: "More than enough" },
    { word: "Arbitrary", meaning: "Based on random choice or personal whim" },
    { word: "Astute", meaning: "Having sharp judgment; shrewd" },
    { word: "Authentic", meaning: "Genuine or real" },
    { word: "Benevolent", meaning: "Well-meaning and kind" },
    { word: "Blatant", meaning: "Very obvious and offensive" },
    { word: "Candid", meaning: "Open and honest" },
    { word: "Capable", meaning: "Having the ability to do something" },
    { word: "Coherent", meaning: "Logical and consistent" },
    { word: "Comprehensive", meaning: "Including all or nearly all details" },
    { word: "Compulsory", meaning: "Required by law or rules" },
    { word: "Conceal", meaning: "To hide or keep something secret" },
    { word: "Conspicuous", meaning: "Easily noticed; standing out" },
    { word: "Controversial", meaning: "Causing public disagreement" },
    { word: "Credible", meaning: "Believable or trustworthy" },
    { word: "Cynical", meaning: "Distrustful of others' motives" },
    { word: "Deceptive", meaning: "Misleading or dishonest" },
    { word: "Diligent", meaning: "Hardworking and careful" },
    { word: "Diverse", meaning: "Showing variety or differences" },
    { word: "Eccentric", meaning: "Unusual or quirky in behavior" },
    { word: "Efficient", meaning: "Achieving maximum productivity with minimum effort" },
    { word: "Elaborate", meaning: "Detailed and complex" },
    { word: "Elusive", meaning: "Hard to find or understand" },
    { word: "Empathetic", meaning: "Showing an ability to understand others' feelings" },
    { word: "Excessive", meaning: "More than what is necessary" },
    { word: "Explicit", meaning: "Clearly stated or shown" },
    { word: "Exquisite", meaning: "Extremely beautiful and delicate" },
    { word: "Feasible", meaning: "Possible to do or achieve" },
    { word: "Flawless", meaning: "Without any imperfections" },
    { word: "Futile", meaning: "Incapable of producing any result; pointless" },
    { word: "Grim", meaning: "Very serious or gloomy" },
    { word: "Hindrance", meaning: "Something that provides resistance or obstruction" },
    { word: "Hypothetical", meaning: "Based on assumptions or theory" },
    { word: "Imminent", meaning: "About to happen" },
    { word: "Impartial", meaning: "Unbiased and fair" },
    { word: "Indispensable", meaning: "Absolutely necessary" },
    { word: "Innovative", meaning: "Introducing new ideas or methods" },
    { word: "Intricate", meaning: "Very detailed and complicated" },
    { word: "Intuitive", meaning: "Based on instinct rather than logic" },
    { word: "Inevitable", meaning: "Certain to happen; unavoidable" },
    { word: "Irrelevant", meaning: "Not related to the subject at hand" },
    { word: "Lucid", meaning: "Clear and easy to understand" },
    { word: "Meticulous", meaning: "Showing great attention to detail" },
    { word: "Monotonous", meaning: "Dull and lacking variety" },
    { word: "Negligent", meaning: "Failing to take proper care" },
    { word: "Obsolete", meaning: "No longer in use; outdated" },
    { word: "Optimistic", meaning: "Expecting good things to happen" },
    { word: "Ostentatious", meaning: "Intended to attract attention; showy" },
    { word: "Paradox", meaning: "A statement that seems contradictory but may be true" },
    { word: "Perceptive", meaning: "Having insight or understanding" },
    { word: "Perseverance", meaning: "Persistence in doing something despite difficulty" },
    { word: "Placid", meaning: "Calm and peaceful" },
    { word: "Plausible", meaning: "Seeming reasonable or probable" },
    { word: "Proficient", meaning: "Skilled in doing something" },
    { word: "Prolonged", meaning: "Continuing for a long time" },
    { word: "Prudent", meaning: "Acting with care and thought for the future" },
    { word: "Receptive", meaning: "Willing to consider new ideas" },
    { word: "Reluctant", meaning: "Unwilling or hesitant" },
    { word: "Resilient", meaning: "Able to recover quickly from difficulties" },
    { word: "Sophisticated", meaning: "Worldly and refined" },
    { word: "Subtle", meaning: "Not obvious or easily noticeable" },
    { word: "Tangible", meaning: "Capable of being touched or felt" },
    { word: "Tedious", meaning: "Boring and repetitive" },
    { word: "Tenuous", meaning: "Very weak or slight" },
    { word: "Trivial", meaning: "Of little importance" },
    { word: "Vague", meaning: "Not clear or specific" },
    { word: "Versatile", meaning: "Able to adapt to different tasks" },
    { word: "Viable", meaning: "Capable of working successfully" },
    { word: "Wary", meaning: "Cautious and watchful" },
    { word: "Whimsical", meaning: "Playfully unusual or fanciful" },
    { word: "Zealous", meaning: "Passionate and enthusiastic" }
  ];

  export const vocabularyWords = [
    { word: "Bright", meaning: "Full of light" },
    { word: "Brief", meaning: "Short in time" },
    { word: "Brave", meaning: "Showing courage" },
    { word: "Quiet", meaning: "Making little noise" },
    { word: "Gentle", meaning: "Kind and soft" },
    { word: "Fierce", meaning: "Very strong or violent" },
    { word: "Polite", meaning: "Showing good manners" },
    { word: "Lazy", meaning: "Not wanting to work" },
    { word: "Neat", meaning: "Clean and tidy" },
    { word: "Tense", meaning: "Stressed or nervous" },
    { word: "Calm", meaning: "Relaxed and peaceful" },
    { word: "Massive", meaning: "Very large" },
    { word: "Precise", meaning: "Exact or accurate" },
    { word: "Harsh", meaning: "Rough or severe" },
    { word: "Fragile", meaning: "Easily broken or damaged" },
    { word: "Dull", meaning: "Not bright or sharp" },
    { word: "Pale", meaning: "Light in color" },
    { word: "Rapid", meaning: "Happening quickly" },
    { word: "Proud", meaning: "Feeling good about something" },
    { word: "Rare", meaning: "Not common" },
    { word: "Admire", meaning: "To respect or like someone" },
    { word: "Argue", meaning: "To disagree strongly" },
    { word: "Blame", meaning: "To say someone is at fault" },
    { word: "Borrow", meaning: "To take and use temporarily" },
    { word: "Capture", meaning: "To catch and hold" },
    { word: "Chase", meaning: "To run after something" },
    { word: "Create", meaning: "To make something new" },
    { word: "Decide", meaning: "To make a choice" },
    { word: "Discover", meaning: "To find something new" },
    { word: "Discuss", meaning: "To talk about something" },
    { word: "Explain", meaning: "To make something clear" },
    { word: "Freeze", meaning: "To turn into ice" },
    { word: "Guess", meaning: "To try to answer without knowing" },
    { word: "Improve", meaning: "To make better" },
    { word: "Invent", meaning: "To create something new" },
    { word: "Join", meaning: "To connect or participate" },
    { word: "Obey", meaning: "To follow rules or instructions" },
    { word: "Pretend", meaning: "To act as if something is true" },
    { word: "Protect", meaning: "To keep safe" },
    { word: "Search", meaning: "To look for something" },
    { word: "Journey", meaning: "A trip from one place to another" },
    { word: "Effort", meaning: "Hard work or attempt" },
    { word: "Danger", meaning: "A situation that is not safe" },
    { word: "Victory", meaning: "Winning in a competition" },
    { word: "Wisdom", meaning: "Knowledge and good judgment" },
    { word: "Desire", meaning: "A strong wish for something" },
    { word: "Kindness", meaning: "Being nice and caring" },
    { word: "Freedom", meaning: "The ability to do what you want" },
    { word: "Patience", meaning: "The ability to wait calmly" },
    { word: "Curiosity", meaning: "A desire to learn or know" },
    { word: "Neighbor", meaning: "A person living nearby" },
    { word: "Guest", meaning: "Someone invited to visit" },
    { word: "Leader", meaning: "Someone in charge" },
    { word: "Artist", meaning: "Someone who creates art" },
    { word: "Scholar", meaning: "Someone who studies a lot" },
    { word: "Stranger", meaning: "Someone you don’t know" },
    { word: "Opponent", meaning: "Someone on the other side in a game or debate" },
    { word: "Partner", meaning: "Someone who works with you" },
    { word: "Villager", meaning: "A person from a small town" },
    { word: "Audience", meaning: "A group of people watching something" },
    { word: "Blossom", meaning: "A flower or to flower" },
    { word: "Breeze", meaning: "A gentle wind" },
    { word: "Cave", meaning: "A hollow space in a mountain or ground" },
    { word: "Desert", meaning: "A dry, sandy area" },
    { word: "Island", meaning: "Land surrounded by water" },
    { word: "Meadow", meaning: "A grassy field" },
    { word: "Peak", meaning: "The top of a mountain" },
    { word: "Shore", meaning: "The land along a body of water" },
    { word: "Stream", meaning: "A small flowing river" },
    { word: "Valley", meaning: "A low area between hills or mountains" },
    { word: "Ambition", meaning: "A strong desire to achieve something" },
    { word: "Chaos", meaning: "Complete disorder" },
    { word: "Justice", meaning: "Fair treatment" },
    { word: "Loyalty", meaning: "Being faithful" },
    { word: "Confidence", meaning: "Belief in yourself" },
    { word: "Harmony", meaning: "Peaceful agreement" },
    { word: "Strength", meaning: "The quality of being strong" },
    { word: "Balance", meaning: "Equal distribution" },
    { word: "Passion", meaning: "Strong feeling or emotion" },
    { word: "Silence", meaning: "Complete quietness" },
    { word: "Adjust", meaning: "To change slightly for a better fit" },
    { word: "Appreciate", meaning: "To value or be grateful for something" },
    { word: "Confirm", meaning: "To make sure something is true" },
    { word: "Define", meaning: "To explain the meaning of something" },
    { word: "Deliver", meaning: "To bring something to someone" },
    { word: "Expand", meaning: "To make larger" },
    { word: "Ignore", meaning: "To not pay attention" },
    { word: "Manage", meaning: "To control or deal with something" },
    { word: "Realize", meaning: "To become aware of something" },
    { word: "Suggest", meaning: "To recommend something" },
    { word: "Alert", meaning: "Being watchful and ready" },
  { word: "Bold", meaning: "Brave and confident" },
  { word: "Charming", meaning: "Attractive and pleasant" },
  { word: "Clumsy", meaning: "Not graceful in movement" },
  { word: "Confident", meaning: "Having trust in yourself" },
  { word: "Delicate", meaning: "Easily broken or damaged" },
  { word: "Eager", meaning: "Very excited to do something" },
  { word: "Enormous", meaning: "Extremely large" },
  { word: "Foolish", meaning: "Lacking good sense" },
  { word: "Generous", meaning: "Willing to give more than needed" },
  { word: "Grateful", meaning: "Thankful for something" },
  { word: "Humble", meaning: "Not proud; modest" },
  { word: "Loyal", meaning: "Faithful to someone or something" },
  { word: "Mature", meaning: "Fully grown or developed" },
  { word: "Mysterious", meaning: "Difficult to understand or explain" },
  { word: "Optimistic", meaning: "Expecting good things to happen" },
  { word: "Precious", meaning: "Very valuable or special" },
  { word: "Relieved", meaning: "Feeling at ease after worry" },
  { word: "Stubborn", meaning: "Not willing to change" },
  { word: "Timid", meaning: "Shy or lacking confidence" },
  { word: "Vivid", meaning: "Bright and clear" },
  { word: "Weary", meaning: "Very tired" },
  { word: "Witty", meaning: "Clever and funny" },
  { word: "Admiration", meaning: "A feeling of respect and liking" },
  { word: "Ambitious", meaning: "Having a strong desire for success" },
  { word: "Courage", meaning: "The ability to face fear or danger" },
  { word: "Determined", meaning: "Having made a firm decision" },
  { word: "Doubtful", meaning: "Feeling uncertain or unsure" },
  { word: "Efficient", meaning: "Doing something without wasting time or effort" },
  { word: "Elegant", meaning: "Graceful and stylish" },
  { word: "Essential", meaning: "Very important or necessary" },
  { word: "Fascinating", meaning: "Very interesting or captivating" },
  { word: "Fortunate", meaning: "Lucky or having good fortune" },
  { word: "Hasty", meaning: "Done quickly without careful thought" },
  { word: "Innocent", meaning: "Not guilty of a crime or offense" },
  { word: "Jealous", meaning: "Feeling envious of someone" },
  { word: "Miserable", meaning: "Very unhappy or uncomfortable" },
  { word: "Nervous", meaning: "Feeling worried or anxious" },
  { word: "Obvious", meaning: "Easily seen or understood" },
  { word: "Patient", meaning: "Able to wait without frustration" },
  { word: "Persistent", meaning: "Continuing despite difficulties" },
  { word: "Polished", meaning: "Shiny or refined" },
  { word: "Regret", meaning: "A feeling of sadness about a mistake" },
  { word: "Reliable", meaning: "Able to be trusted" },
  { word: "Resilient", meaning: "Able to recover quickly from difficulties" },
  { word: "Sincere", meaning: "Honest and truthful" },
  { word: "Skeptical", meaning: "Doubting something is true" },
  { word: "Steady", meaning: "Firm and not changing" },
  { word: "Tranquil", meaning: "Calm and peaceful" },
  { word: "Unique", meaning: "Being one of a kind" },
  { word: "Valuable", meaning: "Worth a lot or very useful" },
  { word: "Versatile", meaning: "Able to do many different things" },
  { word: "Vulnerable", meaning: "Easily hurt or harmed" },
  { word: "Wander", meaning: "To move around without a purpose" },
  { word: "Whisper", meaning: "To speak very softly" },
  { word: "Yearn", meaning: "To have a strong desire for something" },
  { word: "Zealous", meaning: "Full of enthusiasm or energy" }
  ];
  
  export const wordsArray: string[] = [
    "cheaply", "brown", "antinatalist", "implementer", "flip-flop",
    "fretboard", "flip-flopping", "underinvest", "kin", "borage",
    "ammonite", "Elfin", "beefing", "raster", "bracer", "edged",
    "block", "Basilosaurus", "stop-start", "amphora", "parody",
    "amphora", "Disbelieve", "Find", "Brief", "ample", "disdainful",
    "yarding", "edgeways", "axing", "amnion", "update", "lexicon",
    "core", "Holocaust", "Fantabulous", "wrap", "black", "creeping",
    "blank", "brigalow", "ubiquitous", "planet", "sanctions", "edged",
    "edged", "brave", "clued-in", "wretched", "institutionalizing",
    "windproof", "Bigots", "Solemnly", "Solemn", "cadre", "Blabbermouth",
    "communion", "Integration", "Induction", "Zodiac", "Implement",
    "repatriated", "creep", "Drift", "Stampede", "canary", "Blossom",
    "chronicling", "poignant", "kingdom", "stampede", "Blasphemy",
    "Tell-tale", "obtuse", "Trivia", "Solemn", "Somber", "Sickle",
    "envisioning", "dissent", "reciprocity", "centenary", "fibroblast",
    "crepe", "draughty", "Pragmatic", "Sophisticated", "Sabotage",
    "Tree", "Chirp", "neologism", "naive", "approbation", "spared",
    "contemporary", "grappled", "bestiaries", "accorded", "chronicle",
    "concise", "Unprecedented", "Unhinged", "earmarked", "gryphons",
    "chroniclers", "Deference", "Malfeasance", "Perfunctory", "Scholar",
    "Villager", "Intriguing", "Insinuating", "Snobbish", "Obstetrics",
    "fore", "prudence", "Colossus", "subdued", "quash", "spree", "tepid",
    "tumble", "bolster", "bolstering", "Feud", "pernicious", "affluence",
    "anecdotal", "Opponent", "perceptual", "culinary", "Meadow", "envy",
    "reverence", "Persistence", "Grit", "Cognitive", "Dissertation",
    "Wrestled", "Anxious", "Therapeutic", "Spontaneity", "Intertwine",
    "Deities", "allusive", "indelible", "Evangelical", "eschewed",
    "Enigmatic", "Stampede", "Naive", "Bliss", "Fazed", "Reared", "Rote",
    "Strewn", "Enigma", "Delegated", "Delegate", "Damning", "Stampede",
    "Slog", "Riled", "Jacaranda", "Puffs", "Reggae", "Woozy", "Whipped",
    "Torse", "Torso", "Hunched", "Thwacked", "Poised", "Ambled", "Abounded",
    "Impinged", "Amicable", "Thronging", "Deterred", "Aplomb", "Caveats",
    "Patted", "Strung", "Mayhem", "Lurching", "Clasped", "Idly", "Heaving",
    "Stew", "Glared", "Glint", "Yanking", "Ase", "Awe", "Coddled", "Fathom",
    "grappling", "Manipulation", "Deceive", "Pensive", "Grave", "Beady",
    "Savoury", "Lauded", "Morph", "Staunchly", "Patriarchal", "Accruing",
    "Reassert", "Assert", "Pursue", "Relent", "Potent", "Grievous",
    "Acquaintance", "strayed", "haven", "purported", "relentless",
    "obscuring", "Stampede", "crave", "Impeccably"
  ];
  
  export const gameWords = [
    // Little Harder Words
    { word: "Abandon", meaning: "Leave completely" },
    { word: "Ability", meaning: "Skill or talent" },
    { word: "Absorb", meaning: "Take in (liquid, knowledge)" },
    { word: "Abundant", meaning: "Plentiful" },
    { word: "Accomplish", meaning: "Achieve or complete" },
    { word: "Accurate", meaning: "Correct, exact" },
    { word: "Acknowledge", meaning: "Recognize or admit" },
    { word: "Adapt", meaning: "Adjust to new conditions" },
    { word: "Adequate", meaning: "Enough, sufficient" },
    { word: "Admire", meaning: "Respect or approve" },
    { word: "Benefit", meaning: "Advantage or gain" },
    { word: "Bold", meaning: "Confident, brave" },
    { word: "Brief", meaning: "Short in time" },
    { word: "Brilliant", meaning: "Very bright or intelligent" },
    { word: "Burden", meaning: "Heavy load (physical or emotional)" },
    { word: "Capable", meaning: "Having the ability" },
    { word: "Challenge", meaning: "Difficult task" },
    { word: "Circumstance", meaning: "Situation or condition" },
    { word: "Clarify", meaning: "Make clear" },
    { word: "Commit", meaning: "Dedicate or pledge" },
    { word: "Decade", meaning: "10 years" },
    { word: "Decent", meaning: "Acceptable, good enough" },
    { word: "Declare", meaning: "Announce officially" },
    { word: "Defend", meaning: "Protect from harm" },
    { word: "Deliberate", meaning: "Intentional" },
    { word: "Eager", meaning: "Very interested or excited" },
    { word: "Efficient", meaning: "Working well without waste" },
    { word: "Eliminate", meaning: "Remove completely" },
    { word: "Emphasize", meaning: "Stress importance" },
    { word: "Encounter", meaning: "Unexpected meeting" },
    { word: "Familiar", meaning: "Well-known" },
    { word: "Flexible", meaning: "Able to bend or adapt" },
    { word: "Frequent", meaning: "Happening often" },
    { word: "Frustrate", meaning: "Make annoyed or upset" },
    { word: "Fundamental", meaning: "Basic, essential" },
    { word: "Generate", meaning: "Produce or create" },
    { word: "Genuine", meaning: "Real, sincere" },
    { word: "Gradual", meaning: "Happening slowly" },
    { word: "Grasp", meaning: "Understand or hold firmly" },
    { word: "Guarantee", meaning: "Promise or assurance" },
    { word: "Hesitate", meaning: "Pause before acting" },
    { word: "Hostile", meaning: "Unfriendly, aggressive" },
    { word: "Humble", meaning: "Modest, not proud" },
    { word: "Identify", meaning: "Recognize or name" },
    { word: "Ignore", meaning: "Pay no attention" },
    { word: "Impact", meaning: "Strong effect" },
    { word: "Improve", meaning: "Make better" },
    { word: "Influence", meaning: "Affect someone's actions" },
    { word: "Justify", meaning: "Give a good reason" },
    { word: "Knowledge", meaning: "Information, understanding" },
    { word: "Lack", meaning: "Not having enough" },
    { word: "Latter", meaning: "The second of two" },
    { word: "Logical", meaning: "Reasonable, sensible" },
    { word: "Maintain", meaning: "Keep in good condition" },
    { word: "Major", meaning: "Very important" },
    { word: "Minor", meaning: "Less important" },
    { word: "Mature", meaning: "Fully developed" },
    { word: "Necessary", meaning: "Needed, essential" },
    { word: "Neglect", meaning: "Fail to care for" },
    { word: "Numerous", meaning: "Many" },
    { word: "Objective", meaning: "Goal or unbiased" },
    { word: "Obvious", meaning: "Clear, easy to see" },
    { word: "Occur", meaning: "Happen" },
    { word: "Particular", meaning: "Specific" },
    { word: "Persuade", meaning: "Convince" },
    { word: "Potential", meaning: "Possible ability" },
    { word: "Precise", meaning: "Exact" },
    { word: "Prior", meaning: "Earlier" },
    { word: "Quality", meaning: "How good something is" },
    { word: "Quantity", meaning: "Amount" },
    { word: "Rare", meaning: "Not common" },
    { word: "Reasonable", meaning: "Fair, logical" },
    { word: "Recent", meaning: "Happening not long ago" },
    { word: "Reduce", meaning: "Make smaller" },
    { word: "Reject", meaning: "Refuse to accept" },
    { word: "Scarce", meaning: "In short supply" },
    { word: "Significant", meaning: "Important" },
    { word: "Similar", meaning: "Almost the same" },
    { word: "Source", meaning: "Where something comes from" },
    { word: "Specific", meaning: "Exact, detailed" },
    { word: "Temporary", meaning: "Not permanent" },
    { word: "Tend", meaning: "Be likely to do" },
    { word: "Threat", meaning: "Possible danger" },
    { word: "Trend", meaning: "General direction of change" },
    { word: "Unique", meaning: "One of a kind" },
    { word: "Urgent", meaning: "Needing immediate action" },
    { word: "Valid", meaning: "Legally or logically acceptable" },
    { word: "Vary", meaning: "Differ in size/amount" },
    { word: "Visible", meaning: "Able to be seen" },
    { word: "Willing", meaning: "Ready to do something" },
  
    // Advanced Words
    { word: "Aberration", meaning: "A deviation from the norm" },
    { word: "Abstain", meaning: "Refrain from doing something" },
    { word: "Adept", meaning: "Highly skilled" },
    { word: "Adversity", meaning: "Difficulties or misfortune" },
    { word: "Aesthetic", meaning: "Concerned with beauty" },
    { word: "Alacrity", meaning: "Eagerness and enthusiasm" },
    { word: "Aloof", meaning: "Emotionally distant" },
    { word: "Ambiguous", meaning: "Unclear or open to multiple interpretations" },
    { word: "Ameliorate", meaning: "Make something better" },
    { word: "Anomaly", meaning: "Something unusual" },
    { word: "Belligerent", meaning: "Hostile and aggressive" },
    { word: "Benevolent", meaning: "Kind and generous" },
    { word: "Bequeath", meaning: "Pass something on (e.g., inheritance)" },
    { word: "Berate", meaning: "Scold harshly" },
    { word: "Brevity", meaning: "Concise and exact use of words" },
    { word: "Brusque", meaning: "Abrupt in manner" },
    { word: "Burgeon", meaning: "Grow or flourish rapidly" },
    { word: "Cacophony", meaning: "Harsh, discordant sound" },
    { word: "Cajole", meaning: "Persuade with flattery" },
    { word: "Capricious", meaning: "Prone to sudden changes" },
    { word: "Censure", meaning: "Strong criticism" },
    { word: "Chastise", meaning: "Punish severely" },
    { word: "Circumspect", meaning: "Cautious and prudent" },
    { word: "Clandestine", meaning: "Kept secret" },
    { word: "Cogent", meaning: "Clear, logical, convincing" },
    { word: "Colloquial", meaning: "Informal speech" },
    { word: "Conundrum", meaning: "A difficult problem" },
    { word: "Debilitate", meaning: "Weaken severely" },
    { word: "Deleterious", meaning: "Harmful" },
    { word: "Demagogue", meaning: "A manipulative leader" },
    { word: "Deride", meaning: "Mock or ridicule" },
    { word: "Despondent", meaning: "Feeling hopeless" },
    { word: "Diatribe", meaning: "A bitter verbal attack" },
    { word: "Didactic", meaning: "Intended to teach" },
    { word: "Disparate", meaning: "Fundamentally different" },
    { word: "Disseminate", meaning: "Spread widely" },
    { word: "Dogmatic", meaning: "Stubbornly opinionated" },
    { word: "Ebullient", meaning: "Full of energy and enthusiasm" },
    { word: "Egregious", meaning: "Outstandingly bad" },
    { word: "Elucidate", meaning: "Make clear" },
    { word: "Empirical", meaning: "Based on observation" },
    { word: "Enervate", meaning: "Drain energy" },
    { word: "Enigma", meaning: "A mystery" },
    { word: "Ephemeral", meaning: "Lasting a short time" },
    { word: "Equanimity", meaning: "Calm under pressure" },
    { word: "Esoteric", meaning: "Understood by few" },
    { word: "Euphemism", meaning: "A mild term for something harsh" },
    { word: "Fastidious", meaning: "Very attentive to detail" },
    { word: "Fervent", meaning: "Passionate" },
    { word: "Flippant", meaning: "Lacking seriousness" },
    { word: "Florid", meaning: "Excessively intricate" },
    { word: "Foment", meaning: "Stir up trouble" },
    { word: "Fortuitous", meaning: "Happening by chance" },
    { word: "Frugal", meaning: "Economical, avoiding waste" },
    { word: "Furtive", meaning: "Secretive" },
    { word: "Garrulous", meaning: "Excessively talkative" },
    { word: "Germane", meaning: "Relevant to the subject" },
    { word: "Grandiose", meaning: "Overly elaborate" },
    { word: "Gratuitous", meaning: "Unnecessary, uncalled for" },
    { word: "Gregarious", meaning: "Sociable" },
    { word: "Harangue", meaning: "A lengthy and aggressive speech" },
    { word: "Hedonist", meaning: "Someone who seeks pleasure" },
    { word: "Hiatus", meaning: "A pause or gap" },
    { word: "Hyperbole", meaning: "Exaggeration for effect" },
    { word: "Iconoclast", meaning: "Someone who attacks traditions" },
    { word: "Idiosyncratic", meaning: "Peculiar to an individual" },
    { word: "Impecunious", meaning: "Lacking money" },
    { word: "Impetuous", meaning: "Acting without thinking" },
    { word: "Incontrovertible", meaning: "Impossible to deny" },
    { word: "Ineffable", meaning: "Too great to be described" },
    { word: "Inscrutable", meaning: "Impossible to understand" },
    { word: "Insipid", meaning: "Lacking flavor or interest" },
    { word: "Intrepid", meaning: "Fearless" },
    { word: "Juxtapose", meaning: "Place side by side for contrast" },
    { word: "Laconic", meaning: "Using few words" },
    { word: "Languid", meaning: "Slow, sluggish" },
    { word: "Lugubrious", meaning: "Looking or sounding sad" },
    { word: "Malleable", meaning: "Easily shaped or influenced" },
    { word: "Maverick", meaning: "An independent thinker" },
    { word: "Mellifluous", meaning: "Sweet-sounding" },
    { word: "Meticulous", meaning: "Extremely careful" },
    { word: "Misanthrope", meaning: "A person who dislikes humanity" },
    { word: "Nebulous", meaning: "Vague or unclear" },
    { word: "Nefarious", meaning: "Wicked or evil" },
    { word: "Nonchalant", meaning: "Casually indifferent" },
    { word: "Obfuscate", meaning: "Deliberately confuse" },
    { word: "Ostentatious", meaning: "Showy to impress" },
    { word: "Ostracize", meaning: "Exclude from a group" },
    { word: "Paragon", meaning: "A model of excellence" },
    { word: "Paucity", meaning: "A scarcity" },
    { word: "Pedantic", meaning: "Overly concerned with details" },
    { word: "Perfunctory", meaning: "Done without enthusiasm" },
    { word: "Placate", meaning: "Make someone less angry" },
    { word: "Precarious", meaning: "Not securely held" },
    { word: "Proclivity", meaning: "A natural tendency" },
    { word: "Prosaic", meaning: "Dull, unimaginative" },
    { word: "Quixotic", meaning: "Unrealistically idealistic" },
    { word: "Recalcitrant", meaning: "Stubbornly resistant" },
    { word: "Repudiate", meaning: "Reject as invalid" },
    { word: "Rhetoric", meaning: "Persuasive speaking" },
    { word: "Sagacious", meaning: "Wise" },
    { word: "Salient", meaning: "Most noticeable" },
    { word: "Sardonic", meaning: "Mockingly cynical" },
    { word: "Spurious", meaning: "False or fake" },
    { word: "Surreptitious", meaning: "Secretive" },
    { word: "Tenuous", meaning: "Very weak" },
    { word: "Trepidation", meaning: "Fear or anxiety" },
    { word: "Ubiquitous", meaning: "Present everywhere" },
    { word: "Unctuous", meaning: "Excessively flattering" },
    { word: "Vacillate", meaning: "Waver between opinions" },
    { word: "Venerate", meaning: "Regard with great respect" },
    { word: "Veracity", meaning: "Truthfulness" },
    { word: "Whet", meaning: "Sharpen (e.g., appetite)" },
    { word: "Zealous", meaning: "Passionately devoted" }
  ];
  
